# Data
path: /content/drive/MyDrive/Especializacion_IA/CVwDL_20233/ProyectoFinal/train_custom/data
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Keypoints
kpt_shape: [18, 2]  # [number of keypoints, number of dim]
flip_idx: [0, 1, 5, 6, 7, 2, 3, 4, 11, 12, 13, 8, 9, 10, 15, 14, 17, 16]

# Classes
names:
  0: human
